(define (mul a b)
    (define (double x) (* x 2))
    (define (halve x) (/ x 2))
    (define (even? n) (= (remainder n 2) 0))
    (define (mul-iter a b res)
        (cond ((= b 0) res)
            ((even? b) (mul-iter (double a) (halve b) res))
            (else (mul-iter a (- b 1) (+ res a)))
            )
        )
    (mul-iter a b 0)
    )
(mul 0 2)