; efficiency: (theta (sqrt n))
(define (prime? n) (= n (smallest-divisor n)))
(define (smallest-divisor n)
    (define (divide? n divisor) (= (remainder n divisor) 0))
    (define (check-divisor n divisor)
        (cond ((> (square divisor) n) n)
            ((divide? n divisor) divisor)
            (else (check-divisor n (+ divisor 1)))
            ))
    (check-divisor n 2)
    )
(prime? 11)